### PR TITLE
Add support to rails 5

### PR DESCRIPTION
**Pull request by rodrigoulisses**

### CODE REVIEW

**Comment by lucasmazza** [comment]
@rodrigoulisses thanks for the PR, can you please take a look on the Travis failures so we can merge this in? Thanks!

**Comment by rodrigoulisses** [comment]
@lucasmazza the failures was corrected.

**Comment by lucasmazza** [comment]
@rodrigoulisses thanks!

**Comment by carlosantoniodasilva** [comment]
:green_heart::yellow_heart::heart::blue_heart::purple_heart:

**Comment by alto** [comment]
@carlosantoniodasilva Thanks for this gem, and your time for this!

Can we expect to have a new release any time soon? We would like to switch over to Rails 5, and not using an unreleased version.

**Comment by carlosantoniodasilva** [comment]
@alto I totally forgot to get a new gem released, thanks for the ping.

v0.2.3 is out with support to Rails 5!

**Comment by alto** [comment]
@carlosantoniodasilva Great, thanks a lot!

**Pull request merged**
